# Input/output configuration
base_dir: /scratch/gpfs/jdezoort/gnns-for-tracking/graph_construction
input_dir: /tigress/jdezoort/codalab/train_1
output_dir: /scratch/gpfs/jdezoort/gnns-for-tracking/graphs/train1_ptmin0p8
module_map_dir:
n_files: 1000

# Graph building configuration
selection:
    pt_min: 0.8 # GeV
    phi_slope_max: 0.005
    z0_max: 200
    dR_max: 1.7
    uv_approach_max: 0.0015
    n_phi_sectors: 6
    n_eta_sectors: 6
    phi_overlap: 0.1
    eta_overlaps: 0.13
    eta_range: [-4, 4]
    endcaps: true
    remove_noise: true
    remove_duplicates: false
    use_module_map: false

######################################################################
##               RECOMMENDED GRAPH CONSTRUCTION PARAMS              ##
######################################################################
# --------------------------------------------------------------------
#  pt [GeV]  phi_slope [1/mm]  z0 [mm]  dR [a.u.]  uv_approach [1/mm]
# --------------------------------------------------------------------
#  0.0       0.005             200      1.7        0.0015
#
#  (gives 0.987 efficiency and 0.264 purity for >0.8GeV tracks)
#  (gives 0.988 efficiency and 0.335 purity for >1.0GeV tracks)
#
